---
title: "eda"
output: html_document
---

```{r}
#### read in data ####
heart <- read.csv('Framingham Heart Data.csv')
summary(heart)
## remove na data
heart <- heart[!(is.na(heart$Height) | is.na(heart$Weight) | is.na(heart$Smoking) | is.na(heart$Cholesterol)),]


#### format columns (type I censoring) ####
heart$d <- heart$AgeAtDeath - heart$AgeAtStart
heart$c <- ifelse(heart$Status == 'Alive', 0, 1)
tc <- max(heart$d, na.rm = T)
heart$x <- ifelse(is.na(heart$d), tc, heart$d)
#### plots ####
library(survival)
km <- survfit(Surv(heart$x, heart$c) ~ 1, type = 'kaplan-meier')
## survival plot
plot(km$time,km$surv, type="s",xlab="Time",ylab="Survival",
     main = 'Framingham Heart Data Survival Curve')
skm <- summary(km)
df <- data.frame(skm$time, skm$n.risk, skm$n.event, round(skm$surv, 2), round(skm$lower, 2), round(skm$upper, 2))
colnames(df) <- c('Time', '# at risk', '# of events', 'Survival Rate', '95% CI Lower', '95% CI Upper')

library(knitr)
### survival summary table
kable(df)

table(heart$Smoking_Status)
### variable formatting
summary(heart)
heart$BP_level <- ifelse(heart$Systolic <= 129 & heart$Diastolic <= 80, 'Normal', 'High')
heart$Chol_Level <- ifelse(heart$Cholesterol <= 239, 'Normal', 'High')
heart$Smoke_Binary <- ifelse(heart$Smoking_Status == 'Non-smoker', 'No', 'Yes')
heart$opt_weight <- (heart$Weight / heart$MRW..Metropolitan.Relative.desired..Weight.) - 1
heart$DeathType <- ifelse(heart$Status == 'Alive', 'Alive',
                          ifelse(heart$DeathCause %in% c('Coronary Heart Disease'), 'Heart_Disease', 'Other'))
s_heart <- split(heart, heart$DeathType)



### create table of summary of explanatory variables
create_row <- function(df){
sum_vec <- c(round(mean(df$Sex == 'Female'),2), 
             paste(round(mean(df$AgeAtStart, na.rm = T),2), ' (', round(sd(df$AgeAtStart, na.rm = T),2), ')', sep = ''),
             paste(round(mean(df$Height, na.rm = T),2), ' (', round(sd(df$Height, na.rm = T),2), ')', sep = ''),
             paste(round(mean(df$Weight, na.rm = T),2), ' (', round(sd(df$Weight, na.rm = T),2), ')', sep = ''),
             paste(round(mean(df$opt_weight, na.rm = T),2), ' (', round(sd(df$opt_weight, na.rm = T),2), ')', sep = ''),
             paste(round(mean(df$Diastolic, na.rm = T),2), ' (', round(sd(df$Diastolic, na.rm = T),2), ')', sep = ''),
             paste(round(mean(df$Systolic, na.rm = T),2), ' (', round(sd(df$Systolic, na.rm = T),2), ')', sep = ''),
             round(mean(df$BP_level == 'High', na.rm = T), 2),
             paste(round(mean(df$Cholesterol, na.rm = T),2), ' (', round(sd(df$Cholesterol, na.rm = T),2), ')', sep = ''),
             round(mean(df$Chol_Level == 'High', na.rm = T), 2),
             1-round(mean(df$Smoking_Status == 'Non-smoker'),2))
return(sum_vec)
}
table(heart$DeathType, factor(heart$Chol_Level))
summary(factor(s_heart$Alive$Chol_Level))

Total <- create_row(heart)
Alive <- create_row(s_heart$Alive)
Dead_h  <- create_row(s_heart$Heart_Disease)
Dead_o  <- create_row(s_heart$Other)

df_tab <- data.frame(Total, Alive, Dead_h, Dead_o)
colnames(df_tab) <- c('Total' ,'Alive', 'Death (heart disease)', 'Death (other)')
row.names(df_tab) <- c('% Female', 'Mean Age at Start (SD)',
                       'Mean Height (SD)', 'Mean Weight (SD)',
                       'Mean % from desired weight (SD)',
                       'Mean Diastolic (SD)', 'Mean Systolic (SD)',
                       '% High Blood Pressure',
                       'Mean Cholesterol (SD)', 
                       '% High Cholesterol',
                       '% Smoker')

kable(df_tab)

```


Fit the models

```{r}
head(heart)
library(VGAM)

mm <- data.frame(model.matrix(~ factor(DeathType) + 0, heart))
h2 <- cbind(heart, mm)
names(h2)
cols <- cbind(h2$factor.DeathType.Heart_Disease, h2$factor.DeathType.Other, h2$factor.DeathType.Alive)

## test model
mod1 <- vglm(cols ~ factor(Sex) + AgeAtStart + opt_weight + factor(BP_level) + factor(Chol_Level) + factor(Smoke_Binary),
             family = multinomial,
            data = heart)

summary(mod1)

mod2 <- vglm(cols ~ factor(Sex) + AgeAtStart + factor(BP_level) + factor(Chol_Level) + factor(Smoke_Binary),
             family = multinomial,
            data = heart)

summary(mod2)

## create plot of coefficients
bs <- coef(mod2)
ses <- sqrt(diag(vcov(mod2)))
ul <- bs + 1.96*ses
ll <- bs - 1.96*ses
cbind(ll, ul)
length(bs)

plot(1:length(bs),exp(bs), pch=20, ylim=c(0,3), xlim=c(3.5,12.5),
     xlab='Factor',
     ylab='Exp(Coefficient)',
     xaxt='n',
     main='Exponentiated Model coefficients with 95% CI',
     col = 'black',
     cex = 2)

segments(y1=exp(ul),y0=exp(ll),x0=1:length(bs), lwd = 3, col = 'black')
abline(h=1, lty=2)
c_name <- c('Intercept 1', 'Intercept 2', 'Sex = M:1', 'Sex = M:2', 'Age at start:1', 'Age at start:2',
            'BP = Normal:1', 'BP = Normal:2', 'Chol = Normal:1', 'Chol = Normal:2' ,
            'Smoke = Yes:1', 'Smoke = Yes:2')
axis(1, at = 1:length(bs), labels = c_name, srt = 45)

lines((mod.vis$coefficients[2:7]), pch=20,
     
     col='dark gray',
     type='p')

segments(y1=ul3,y0=ll4,x0=1:6, lwd = 2, col = 'dark gray')

## check ok to remove weight with LRT test
anova(mod2, mod1, test = 'LRT', type = 1)

### check for interactions between weight and other variables
boxplot(heart$opt_weight ~ heart$BP_level)
boxplot(heart$opt_weight ~ heart$Chol_Level)
boxplot(heart$opt_weight ~ heart$DeathType)


### check interaction model


```